### ISSUE TITLE
During Template Parameter Validation Use a better error message

### ISSUE THREAD

**Issue by sedouard** [singhkay/testtemplate#53]
Instead of:
`Template object - paramters.userImageStorageContainerName.description is missing`

Do: 

`Tempalte Parameter userImageStorageContainerName.description is missing`

**Comment by singhkay** [comment]
@sedouard Can we do 

    Template parameter "userImageStorageContainerName" is missing "description" in the metadata property

**Comment by sedouard** [comment]
sure thing, that shouldn't be a problem

**Comment by sedouard** [comment]
https://travis-ci.org/singhkay/testtemplate/builds/92171998 

`AssertionError: 201-fake-new-template/azuredeploy.json - Parameter "vmNamePrefix" is missing its "description" field within the metadata property`

**Comment by sedouard** [comment]
closed via https://github.com/singhkay/testtemplate/commit/51cdbab45b090c01fc28ed5f7149799541985bfa
